// Admin Authentication

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const ADMIN_LOADING = 'ADMIN_LOADING';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';


// Students Admin

export const ADMIN_STUDENTS_LOADING = 'ADMIN_STUDENTS_LOADING';
export const ADMIN_STUDENTS_LOADED = 'ADMIN_STUDENTS_LOADED';
export const ADMIN_STUDENTS_LOAD_ERROR = 'ADMIN_STUDENTS_LOAD_ERROR';

// Unverified Students Admin

export const ADMIN_UNSTUDENTS_LOADING = 'ADMIN_UNSTUDENTS_LOADING';
export const ADMIN_UNSTUDENTS_LOADED = 'ADMIN_UNSTUDENTS_LOADED';
export const ADMIN_UNSTUDENTS_LOAD_ERROR = 'ADMIN_UNSTUDENTS_LOAD_ERROR';


// Single Student Loading

export const ADMIN_STUDENT_LOADING = 'ADMIN_STUDENT_LOADING';
export const ADMIN_STUDENT_LOADED = 'ADMIN_STUDENT_LOADED';
export const ADMIN_STUDENT_LOAD_ERROR = 'ADMIN_STUDENT_LOAD_ERROR';


// Verify Student

export const ADMIN_STUDENT_VERIFYING = 'ADMIN_STUDENT_VERIFYING';
export const ADMIN_STUDENT_VERIFIED = 'ADMIN_STUDENT_VERIFIED';
export const ADMIN_STUDENT_VERIFY_ERROR = 'ADMIN_STUDENT_VERIFY_ERROR';


// Unverify Student

export const ADMIN_STUDENT_UNVERIFYING = 'ADMIN_STUDENT_UNVERIFYING';
export const ADMIN_STUDENT_UNVERIFIED = 'ADMIN_STUDENT_UNVERIFIED';
export const ADMIN_STUDENT_UNVERIFY_ERROR = 'ADMIN_STUDENT_UNVERIFY_ERROR';

// Get Courses

export const ADMIN_COURSES_LOADING = 'ADMIN_COURSES_LOADING';
export const ADMIN_COURSES_LOADED = 'ADMIN_COURSES_LOADED';
export const ADMIN_COURSES_LOAD_ERROR = 'ADMIN_COURSES_LOAD_ERROR';

// Delete Course

export const ADMIN_COURSE_DELETEING = 'ADMIN_COURSE_DELETEING';
export const ADMIN_COURSE_DELETED = 'ADMIN_COURSE_DELETED';
export const ADMIN_COURSE_DELETE_ERROR = 'ADMIN_COURSE_DELETE_ERROR';

// Adding Course

export const ADMIN_COURSE_ADDING = 'ADMIN_COURSE_ADDING';
export const ADMIN_COURSE_ADDED = 'ADMIN_COURSE_ADDED';
export const ADMIN_COURSE_ADD_ERROR = 'ADMIN_COURSE_ADD_ERROR';

// Edit Course

export const ADMIN_COURSE_EDITING = 'ADMIN_COURSE_EDITING';
export const ADMIN_COURSE_EDITED = 'ADMIN_COURSE_EDITED';
export const ADMIN_COURSE_EDIT_ERROR = 'ADMIN_COURSE_EDIT_ERROR';

