// Admin Authentication

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const ADMIN_LOADING = 'ADMIN_LOADING';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';


// Students Admin

export const ADMIN_STUDENTS_LOADING = 'ADMIN_STUDENTS_LOADING';
export const ADMIN_STUDENTS_LOADED = 'ADMIN_STUDENTS_LOADED';
export const ADMIN_STUDENTS_LOAD_ERROR = 'ADMIN_STUDENTS_LOAD_ERROR';

// Unverified Students Admin

export const ADMIN_UNSTUDENTS_LOADING = 'ADMIN_UNSTUDENTS_LOADING';
export const ADMIN_UNSTUDENTS_LOADED = 'ADMIN_UNSTUDENTS_LOADED';
export const ADMIN_UNSTUDENTS_LOAD_ERROR = 'ADMIN_UNSTUDENTS_LOAD_ERROR';


// Single Student Loading

export const ADMIN_STUDENT_LOADING = 'ADMIN_STUDENT_LOADING';
export const ADMIN_STUDENT_LOADED = 'ADMIN_STUDENT_LOADED';
export const ADMIN_STUDENT_LOAD_ERROR = 'ADMIN_STUDENT_LOAD_ERROR';


// Verify Student

export const ADMIN_STUDENT_VERIFYING = 'ADMIN_STUDENT_VERIFYING';
export const ADMIN_STUDENT_VERIFIED = 'ADMIN_STUDENT_VERIFIED';
export const ADMIN_STUDENT_VERIFY_ERROR = 'ADMIN_STUDENT_VERIFY_ERROR';


// Unverify Student

export const ADMIN_STUDENT_UNVERIFYING = 'ADMIN_STUDENT_UNVERIFYING';
export const ADMIN_STUDENT_UNVERIFIED = 'ADMIN_STUDENT_UNVERIFIED';
export const ADMIN_STUDENT_UNVERIFY_ERROR = 'ADMIN_STUDENT_UNVERIFY_ERROR';

// Get Courses

export const ADMIN_COURSES_LOADING = 'ADMIN_COURSES_LOADING';
export const ADMIN_COURSES_LOADED = 'ADMIN_COURSES_LOADED';
export const ADMIN_COURSES_LOAD_ERROR = 'ADMIN_COURSES_LOAD_ERROR';

// Delete Course

export const ADMIN_COURSE_DELETEING = 'ADMIN_COURSE_DELETEING';
export const ADMIN_COURSE_DELETED = 'ADMIN_COURSE_DELETED';
export const ADMIN_COURSE_DELETE_ERROR = 'ADMIN_COURSE_DELETE_ERROR';

// Adding Course

export const ADMIN_COURSE_ADDING = 'ADMIN_COURSE_ADDING';
export const ADMIN_COURSE_ADDED = 'ADMIN_COURSE_ADDED';
export const ADMIN_COURSE_ADD_ERROR = 'ADMIN_COURSE_ADD_ERROR';

// Edit Course

export const ADMIN_COURSE_EDITING = 'ADMIN_COURSE_EDITING';
export const ADMIN_COURSE_EDITED = 'ADMIN_COURSE_EDITED';
export const ADMIN_COURSE_EDIT_ERROR = 'ADMIN_COURSE_EDIT_ERROR';

// Add Election

export const ADMIN_ELECTION_ADDING = 'ADMIN_ELECTION_ADDING';
export const ADMIN_ELECTION_ADDED = 'ADMIN_ELECTION_ADDED';
export const ADMIN_ELECTION_ADD_ERROR = 'ADMIN_ELECTION_ADD_ERROR';

// Edit Election

export const ADMIN_ELECTION_EDITING = 'ADMIN_ELECTION_EDITING';
export const ADMIN_ELECTION_EDITED = 'ADMIN_ELECTION_EDITED';
export const ADMIN_ELECTION_EDIT_ERROR = 'ADMIN_ELECTION_EDIT_ERROR';

// List Election

export const ADMIN_ELECTION_LOADING = 'ADMIN_ELECTION_LOADING';
export const ADMIN_ELECTION_LOADED = 'ADMIN_ELECTION_LOADED';
export const ADMIN_ELECTION_LOAD_ERROR = 'ADMIN_ELECTION_LOAD_ERROR';

// Delete Election

export const ADMIN_ELECTION_DELETING = 'ADMIN_ELECTION_DELETING';
export const ADMIN_ELECTION_DELETED = 'ADMIN_ELECTION_DELETED';
export const ADMIN_ELECTION_DELETE_ERROR = 'ADMIN_ELECTION_DELETE_ERROR';

// Add Positions

export const ADMIN_POSITION_ADDING = 'ADMIN_POSITION_ADDING';
export const ADMIN_POSITION_ADDED = 'ADMIN_POSITION_ADDED';
export const ADMIN_POSITION_ADD_ERROR = 'ADMIN_POSITION_ADD_ERROR';

// Edit Positions

export const ADMIN_POSITION_EDITING = 'ADMIN_POSITION_EDITING';
export const ADMIN_POSITION_EDITED = 'ADMIN_POSITION_EDITED';
export const ADMIN_POSITION_EDIT_ERROR = 'ADMIN_POSITION_EDIT_ERROR';

// Delete Positions

export const ADMIN_POSITION_DELETING = 'ADMIN_POSITION_DELETING';
export const ADMIN_POSITION_DELETED = 'ADMIN_POSITION_DELETED';
export const ADMIN_POSITION_DELETE_ERROR = 'ADMIN_POSITION_DELETE_ERROR';

// Load Positions

export const ADMIN_POSITION_LOADING = 'ADMIN_POSITION_LOADING';
export const ADMIN_POSITION_LOADED = 'ADMIN_POSITION_LOADED';
export const ADMIN_POSITION_LOAD_ERROR = 'ADMIN_POSITION_LOAD_ERROR';

// Load Candidate

export const ADMIN_CANDIDATE_LOADING = 'ADMIN_CANDIDATE_LOADING';
export const ADMIN_CANDIDATE_LOADED = 'ADMIN_CANDIDATE_LOADED';
export const ADMIN_CANDIDATE_LOAD_ERROR = 'ADMIN_CANDIDATE_LOAD_ERROR';

// Load Candidates

export const ADMIN_CANDIDATES_LOADING = 'ADMIN_CANDIDATES_LOADING';
export const ADMIN_CANDIDATES_LOADED = 'ADMIN_CANDIDATES_LOADED';
export const ADMIN_CANDIDATES_LOAD_ERROR = 'ADMIN_CANDIDATES_LOAD_ERROR';

// Accept Candidate

export const ADMIN_CANDIDATE_VERIFYING = 'ADMIN_CANDIDATE_VERIFYING';
export const ADMIN_CANDIDATE_VERIFIED = 'ADMIN_CANDIDATE_VERIFIED';
export const ADMIN_CANDIDATE_VERIFY_ERROR = 'ADMIN_CANDIDATE_VERIFY_ERROR';

// Reject candidate

export const ADMIN_CANDIDATE_UNVERIFYING = 'ADMIN_CANDIDATE_UNVERIFYING';
export const ADMIN_CANDIDATE_UNVERIFIED = 'ADMIN_CANDIDATE_UNVERIFIED';
export const ADMIN_CANDIDATE_UNVERIFY_ERROR = 'ADMIN_CANDIDATE_UNVERIFY_ERROR';

// Start election

export const ADMIN_ELECTION_STARTING = 'ADMIN_ELECTION_STARTING';
export const ADMIN_ELECTION_STATRTED = 'ADMIN_ELECTION_STATRTED';
export const ADMIN_ELECTION_START_ERROR = 'ADMIN_ELECTION_START_ERROR';

// Delete Student 

export const ADMIN_STUDENT_DELETING = 'ADMIN_STUDENT_DELETING';
export const ADMIN_STUDENT_DELETED = 'ADMIN_STUDENT_DELETED';
export const ADMIN_STUDENT_DELETE_ERROR = 'ADMIN_STUDENT_DELETE_ERROR';

// Update Batch

export const ADMIN_BATCH_UPDATING = 'ADMIN_BATCH_UPDATING';
export const ADMIN_BATCH_UPDATED = 'ADMIN_BATCH_UPDATED';
export const ADMIN_BATCH_UPDATE_ERROR = 'ADMIN_BATCH_UPDATE_ERROR';

// Student Login 1

export const STUDENT_UNIQUEID_VERIFYING = 'STUDENT_UNIQUEID_VERIFYING';
export const STUDENT_UNIQUEID_VERIFIED = 'STUDENT_UNIQUEID_VERIFIED';
export const STUDENT_UNIQUEID_VERIFY_ERROR = 'STUDENT_UNIQUEID_VERIFY_ERROR';

// Student Login 2

export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const STUDENT_LOGOUT_SUCCESS = 'STUDENT_LOGOUT_SUCCESS';
export const STUDENT_LOADED = 'STUDENT_LOADED';
export const STUDENT_LOADING = 'STUDENT_LOADING';
export const STUDENT_AUTH_ERROR = 'STUDENT_AUTH_ERROR';

// Nomination 

export const STUDENT_NOMINATION_ADDING = 'STUDENT_NOMINATION_ADDING';
export const STUDENT_NOMINATION_ADDED = 'STUDENT_NOMINATION_ADDED';
export const STUDENT_NOMINATION_ADD_ERROR = 'STUDENT_NOMINATION_ADD_ERROR';

// Select Course

export const STUDENT_COURSE_SELECTING = 'STUDENT_COURSE_SELECTING';
export const STUDENT_COURSE_SELECTED = 'STUDENT_COURSE_SELECTED';
export const STUDENT_COURSE_SELECT_ERROR = 'STUDENT_COURSE_SELECT_ERROR';

// Select Election

export const STUDENT_ELECTION_SELECTING = 'STUDENT_ELECTION_SELECTING';
export const STUDENT_ELECTION_SELECTED = 'STUDENT_ELECTION_SELECTED';
export const STUDENT_ELECTION_SELECT_ERROR = 'STUDENT_ELECTION_SELECT_ERROR';

// Select Course

export const STUDENT_POSITION_SELECTING = 'STUDENT_POSITION_SELECTING';
export const STUDENT_POSITION_SELECTED = 'STUDENT_POSITION_SELECTED';
export const STUDENT_POSITION_SELECT_ERROR = 'STUDENT_POSITION_SELECT_ERROR';


// register the student

export const STUDENT_REGISTERING= 'STUDENT_REGISTERING';
export const STUDENT_REGISTERD ='STUDENT_REGISTERD';
export const STUDENT_REGISTER_ERROR = 'STUDENT_REGISTER_ERROR';


// canidate 

export const STUDENT_CANDIDATE_LOADING= 'STUDENT_CANDIDATE_LOADING';
export const STUDENT_CANDIDATE_LOADED ='STUDENT_CANDIDATE_LOADED';
export const STUDENT_CANDIDATE_LOAD_ERROR ='STUDENT_CANDIDATE_LOAD_ERROR';


