// Admin Authentication

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const ADMIN_LOADING = 'ADMIN_LOADING';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';


// Students Admin

export const ADMIN_STUDENTS_LOADING = 'ADMIN_STUDENTS_LOADING';
export const ADMIN_STUDENTS_LOADED = 'ADMIN_STUDENTS_LOADED';
export const ADMIN_STUDENTS_LOAD_ERROR = 'ADMIN_STUDENTS_LOAD_ERROR';


// Single Student Loading

export const ADMIN_STUDENT_LOADING = 'ADMIN_STUDENT_LOADING';
export const ADMIN_STUDENT_LOADED = 'ADMIN_STUDENT_LOADED';
export const ADMIN_STUDENT_LOAD_ERROR = 'ADMIN_STUDENT_LOAD_ERROR';